#!/bin/bash
echo "[[ Minecraft 1.5.2 ]]"
if test ! -f "lwjgl.jar"; then
rm -f lwjgl.jar
wget https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar -O lwjgl.jar
fi
if test ! -f "lwjgl_util.jar"; then
rm -f lwjgl_util.jar
wget https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar -O lwjgl_util.jar
fi
if test ! -f "jinput.jar"; then
rm -f jinput.jar
wget https://libraries.minecraft.net/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar -O jinput.jar
fi

if test ! -d "natives/"; then
rm -rf natives
mkdir natives 
cd natives
wget https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-linux.jar -O lwjgl-li
unzip lwjgl-li
cd ..
fi

if test ! -f "minecraft.jar"; then
rm -f minecraft.jar
wget https://launcher.mojang.com/v1/objects/465378c9dc2f779ae1d6e8046ebc46fb53a57968/client.jar -O minecraft.jar
fi

if test ! -d "jre/"; then
rm -rf jre
wget https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u322-b06/OpenJDK8U-jre_x64_linux_hotspot_8u322b06.tar.gz
tar -xzvf OpenJDK8U-jre_x64_linux_hotspot_8u322b06.tar.gz
mv jdk8u322-b06-jre/ jre/
fi

java -Djava.util.Arrays.useLegacyMergeSort=true -Dhttp.proxyHost=betacraft.uk -Djava.library.path=natives/ -cp minecraft.jar:lwjgl.jar:lwjgl_util.jar:jinput.jar net.minecraft.client.Minecraft
exit