#!/bin/bash
echo "[[ Minecraft ]]"
if [[ $1 == "--help" ]]
then
echo "Bash script that starts up Minecraft"
echo "--changeversion : Change the current version of Minecraft that's installed"
echo "--help : Brings up this menu"
exit
fi
if [ -z "$1" ] || ([[ $1 == "--changeversion" ]] && [ -z "$2" ])
then
echo "Username empty!"
echo "If you want to contine with a username, exit the script now via Ctrl+C and launch the script via adding a space after the file name and typing in the username that you want"
echo "For example, if you want to have the name 'Notch' and the script is in a folder called mc on your desktop, you would start the script via '~/Desktop/mc/startmc-linux Notch' "
echo "If you want to continue with a random username, press any other key"
read X
fi
echo "Downloading jar files..."
if test ! -f "lwjgl.jar"; then
rm -f lwjgl.jar
wget https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar -O lwjgl.jar
else
echo "lwjgl.jar already downloaded!"
fi
if test ! -f "lwjgl_util.jar"; then
rm -f lwjgl_util.jar
wget https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar -O lwjgl_util.jar
else
echo "lwjgl_util.jar already downloaded!"
fi
if test ! -f "jinput.jar"; then
rm -f jinput.jar
wget https://libraries.minecraft.net/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar -O jinput.jar
else
echo "jinput.jar already downloaded!"
fi
echo "Downloading natives!"
if test ! -d "natives/"; then
rm -rf natives
mkdir natives 
cd natives
wget https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-linux.jar -O lwjgl-li
unzip lwjgl-li
cd ..
else
echo "Already downloaded!"
fi
clear
if [ ! -f "minecraft.jar" ] || [[ $1 == "--changeversion" ]]; then
rm -f minecraft.jar
echo "What version of minecraft?"
echo "Versions supported : 1.0, 1.1, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.3, 1.3.1, 1.3.2, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.5, 1.5.1, 1.5.2"
read version
echo "Downloading Minecraft version" $version
case "$version" in

	1.0) wget https://launcher.mojang.com/v1/objects/b679fea27f2284836202e9365e13a82552092e5d/client.jar -O minecraft.jar;;
	1.1) wget https://launcher.mojang.com/v1/objects/f690d4136b0026d452163538495b9b0e8513d718/client.jar -O minecraft.jar;;
	1.2) wget https://vault.omniarchive.uk/archive/java/client-release/1.2/pre/1.2-pre.jar -O minecraft.jar;;
	1.2.1) wget https://launcher.mojang.com/v1/objects/c7662ac43dd04bfd677694a06972a2aaaf426505/client.jar -O minecraft.jar;;
	1.2.2) wget https://launcher.mojang.com/v1/objects/1dadfc4de6898751f547f24f72c7271218e4e28f/client.jar -O minecraft.jar;;
	1.2.3) wget https://launcher.mojang.com/v1/objects/5134e433afeba375c00bbdcd8aead1d3222813ee/client.jar -O minecraft.jar;;
	1.2.4) wget https://launcher.mojang.com/v1/objects/ad6d1fe7455857269d4185cb8f24e62cc0241aaf/client.jar -O minecraft.jar;;
	1.2.5) wget https://launcher.mojang.com/v1/objects/4a2fac7504182a97dcbcd7560c6392d7c8139928/client.jar -O minecraft.jar;;
	1.3) wget https://launcher.mojang.com/v1/objects/4dfb8098b39c122f2aad13768d3f0d04db910f12/client.jar -O minecraft.jar;;
	1.3.1) wget https://launcher.mojang.com/v1/objects/33167e71e85ab8e6ddbe168bc67f6ec19d708d62/client.jar -O minecraft.jar;;
	1.3.2) wget https://launcher.mojang.com/v1/objects/c2efd57c7001ddf505ca534e54abf3d006e48309/client.jar -O minecraft.jar;;
	1.4) wget https://launcher.mojang.com/v1/objects/2007097b53d3eb43b2c1f3f78caab4a4ef690c7a/client.jar -O minecraft.jar;;
	1.4.1) wget https://launcher.mojang.com/v1/objects/67604a9c206697032165fc067b6255e333e06275/client.jar -O minecraft.jar;;
	1.4.2) wget https://launcher.mojang.com/v1/objects/42d6744cfbbd2958f9e6688dd6e78d86d658d0d4/client.jar -O minecraft.jar;;
	1.4.3) wget https://launcher.mojang.com/v1/objects/f7274b201219b5729055bf85683eb6ef4f8024b4/client.jar -O minecraft.jar;;
	1.4.4) wget https://launcher.mojang.com/v1/objects/b9b2a9e9adf1bc834647febc93a4222b4fd6e403/client.jar -O minecraft.jar;;
	1.4.5) wget https://launcher.mojang.com/v1/objects/7a8a963ababfec49406e1541d3a87198e50604e5/client.jar -O minecraft.jar;;
	1.4.6) wget https://launcher.mojang.com/v1/objects/116758f41b32e8d1a71a4ad6236579acd724bca7/client.jar -O minecraft.jar;;
	1.4.7) wget https://launcher.mojang.com/v1/objects/53ed4b9d5c358ecfff2d8b846b4427b888287028/client.jar -O minecraft.jar;;
	1.5) wget https://launcher.mojang.com/v1/objects/a3da981fc9b875a51975d8f8100cc0c201c2ce54/client.jar -O minecraft.jar;;
	1.5.1) wget https://launcher.mojang.com/v1/objects/047136381a552f34b1963c43304a1ad4dc0d2d8e/client.jar -O minecraft.jar;;
	1.5.2) wget https://launcher.mojang.com/v1/objects/465378c9dc2f779ae1d6e8046ebc46fb53a57968/client.jar -O minecraft.jar;;

esac
else
echo "Already downloaded!"
fi
echo "Downloading java!"
if test ! -d "jre/"; then
rm -rf jre
wget https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u322-b06/OpenJDK8U-jre_x64_linux_hotspot_8u322b06.tar.gz
tar -xzvf OpenJDK8U-jre_x64_linux_hotspot_8u322b06.tar.gz
mv jdk8u322-b06-jre/ jre/
else
echo "Already downloaded!"
fi
clear
echo "Starting Minecraft! Note: you can only join offline-mode servers"
if [[ $1 == "--changeversion" ]]; then
echo "Username is" $2
./jre/bin/java -Djava.util.Arrays.useLegacyMergeSort=true -Dhttp.proxyHost=betacraft.uk -Djava.library.path=natives/ -cp minecraft.jar:lwjgl.jar:lwjgl_util.jar:jinput.jar net.minecraft.client.Minecraft $2
else
echo "Username is" $1
./jre/bin/java -Djava.util.Arrays.useLegacyMergeSort=true -Dhttp.proxyHost=betacraft.uk -Djava.library.path=natives/ -cp minecraft.jar:lwjgl.jar:lwjgl_util.jar:jinput.jar net.minecraft.client.Minecraft $1
fi
exit
